import { Josefin_Sans} from "next/font/google";
import "./globals.css";
import Navbar from "@/componetns/Navbar";
import Footer from "@/componetns/Footer";

const josefin = Josefin_Sans({
  subsets: ["latin"],
});



export const metadata = {
  title: "WonderLust | Your Travel partner",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${josefin.className}  h-full antialiased`}
    >
      <body >
        <Navbar/>
       <main >
         {children}
       </main>
       <Footer/>
        </body>
    </html>
  );
}
